@baseUrl = http://localhost:4004
@taskId = 5865185b-721d-4840-a83e-7c9559c65709
@user = Basic QXhlbDoxMjM=

@admin = Basic QWRtaW46YWRtaW4xMjM=

### 1) exibe drafts
GET {{baseUrl}}/task/Tasks?$filter=IsActiveEntity eq false
Authorization: 
Content-Type: application/json

### 2) exibe salvos
GET {{baseUrl}}/task/Tasks?$filter=IsActiveEntity eq true

### 3) cria draft
POST {{baseUrl}}/task/Tasks
Authorization: 
Content-Type: application/json

{
  "title": "Teste 1",
  "isArchived": false
}

### 4) edita o draft
PATCH {{baseUrl}}/task/Tasks(ID={{taskId}},IsActiveEntity=false)
Authorization: 
Content-Type: application/json

{
  "title": "Atualizado pelo Axel",
  "isArchived": false
}

### 5) salva/ativa o draft
POST {{baseUrl}}/task/Tasks(ID={{taskId}},IsActiveEntity=false)/draftActivate
Authorization: 
Content-Type: application/json
Accept: application/json

### 6) edita o salvo
PATCH {{baseUrl}}/task/Tasks(ID={{taskId}},IsActiveEntity=true)
Authorization: 
Content-Type: application/json

{
  "title": "Atualizado pelo Axel",
  "isArchived": false
}

### 5) deleta salvo (apenas admins podem deletar)
DELETE {{baseUrl}}/task/Tasks(ID={{taskId}},IsActiveEntity=true)
Authorization: {{admin}}
Accept: application/json

### 6) deleta draft (apenas admins podem deletar)
DELETE {{baseUrl}}/task/Tasks(ID={{taskId}},IsActiveEntity=false)
Authorization: {{admin}}
Accept: application/json